### PR TITLE
Added min, max and steps arguments as an alternative to sizes

### LINKED ISSUE #26: min and max arguments to calculate sizes automatically
Hey! I'm currently attempting to integrate a responsive images loader into html-loader, as currently it just outputs full sized images.

Would you accept a PR enabling this syntax?

```js
require('responsive?min=100&max=300!./myImage.jpg');
```

From there, it'll calculate the best sizes (maybe another argument to say the number of images?), and generate the images. This could be done from html-loader, but I figure it's best to do it from the place that actually accesses the image file so that max can be taken down if necessary.

### PR DESCRIPTION
**Pull request by callumacrae**
closes #26

### CODE REVIEW

**Comment by callumacrae** [comment]
@herrstucki: I'm not sure what's going on with the tests here - could you help me out?

**Comment by alex-ketch** [comment]
@callumacrae You're getting syntax errors in older versions of Node, [See Travis logs](https://travis-ci.org/herrstucki/responsive-loader/jobs/202586933#L559).

I ran into the same problem in a previous PR, see [our discussion](https://github.com/herrstucki/responsive-loader/pull/16#pullrequestreview-4669595).

I had to add a `'use strict'; // eslint-disable-line` at the function level scope.

**Comment by callumacrae** [comment]
Got it. I was confused because I thought the syntax error was in the test file, not index.js. I've moved the use strict statement from the previous PR to cover the entire function, or it's not possible to use `let`.

**Comment by callumacrae** [comment]
Anything I can do to get this merged?

**Comment by TomDeBacker** [comment]
@alex-ketch @herrstucki 
No pressure but alot of people are excited for this!

**Comment by alex-ketch** [comment]
@TomDeBacker I'm afraid you'll have to wait for @herrstucki to chime in.
I imagine he is busy with other commitments, and I'd want to wait for his thoughts about this PR.

I know he's been working on a large PR #29, so he might want to merge that before this.

Sorry for the wait, and thank you for the work @callumacrae.

**Comment by herrstucki** [comment]
Yeah, I'm sorry for the delay! 😓  I've been pretty busy with other things.

First impression is good, although I'm [not yet 100% convinced that it's super-necessary to add more API surface for this relatively trivial use case](https://github.com/herrstucki/responsive-loader/issues/26#issuecomment-271173558). But if this is what a lot of people want, I won't say no I guess 😁 

Two small things:
- Please add a entry to the change log
- I see that you're not doing any rounding. Is that going to be a problem?
- Should `generatedSizes` really take precedent over explicitly defined `sizes`?

As @alex-ketch wrote, #29 is a bigger change but this doesn't depend on it, we just need to make sure we don't forget to add it there as well.

**Comment by callumacrae** [comment]
No rounding probably wouldn't be a problem (I'm honestly not sure), but I've told it to round up so that nothing unexpected happens. I've also changed the order of precedence and added an entry to the changelog.

I never really understood how adding sizes to the webpack config file would have solved the problem: if I have an image which displays full width up to 1280px (*2 for retina), and I have an image which takes up half of an 1000px wide grid—500px—then setting the sizes in the webpack config will only work for one of them.

**Comment by callumacrae** [comment]
Sorry to bump again @herrstucki, but is there anything else I can do to get this merged?

**Comment by callumacrae** [comment]
@herrstucki would you like me to send a PR to the `sharp` branch instead? I figure this PR will break once that one is merged

**Comment by TheLarkInn** [comment]
👋👋👋 @herrstucki, I'm Sean from the webpack team. If there's anything we can do to help support this PR, let us know. Nice work @callumacrae

**Comment by herrstucki** [comment]
Hi @callumacrae, sorry again and thanks for your patience. I just merged and shipped the sharp branch as `v1.0`, so you can rebase against master. I'll be happy to release this in `v1.1`.

👋  and 🙇  for the offer @TheLarkInn

**Comment by callumacrae** [comment]
@herrstucki done! I started again from master instead of rebasing, but I guess it's had the same affect.

I've never used jest or flow before, so let me know if I'm doing anything wrong there.

**Comment by herrstucki** [comment]
Thanks @callumacrae, this looks good 👍 . You missed an edge case where setting `?size` wouldn't override existing min/max options. I fixed it and added some tests for this but I couldn't push to your branch. Can you [give me permissions to do this](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by callumacrae** [comment]
@herrstucki allow edits from maintainers is already checked, but i've given you collaborator access to my repo now too.

**Comment by herrstucki** [comment]
@callumacrae it seems the git origin wasn't set up properly. Sorry for the confusion 😄

**Comment by callumacrae** [comment]
Cool, those changes look good :+1:

Any particular reason you're not willing to have an .editorconfig file in this project? or is it just not suitable for this PR?

**Comment by herrstucki** [comment]
@callumacrae I'm generally not against having it but I assumed it slipped in by accident and wasn't really related to this PR. Also, I'd probably rather use [prettier](https://github.com/prettier/prettier) to format the code. Not sure if both are needed.

Thanks again! Released as `v1.1.0` 🚢

**Comment by callumacrae** [comment]
Awesome 🎉 thanks!

**Pull request merged**
