### PR TITLE
Added outputPath and publicPath options

### PR DESCRIPTION
**Pull request by DomenicoCardillo**
Added these options like file loader: https://github.com/webpack-contrib/file-loader
These options allow to change output path and public path, instead of specify it in the options "name", like suggested in this issues: https://github.com/herrstucki/responsive-loader/issues/47

### CODE REVIEW

**Comment by DomenicoCardillo** [comment]
Hi, thanks for the fast answer. 
I've merged the README, I made a fix on my code and I wrote the tests for these two new option.

Thanks.

**Comment by herrstucki** [comment]
In fact, I wonder if we can use file-loader directly to avoid re-implementing the same logic.

**Comment by DomenicoCardillo** [comment]
I could implement the same logic of file-loader but if you find a solution about avoid to do that, it would be great. I'll follow https://github.com/webpack-contrib/file-loader/issues/262

**Comment by cyrilwanner** [comment]
Thank you for this change, this is exactly what I was looking for! I tested it in my project and it works like a charm, I could simply copy the options of the file-loader which I'm already using.

@herrstucki thank you for this loader :) Is there an ETA when this change will leave the beta status/tag? I'm planning to add support for the responsive-loader to my image optimization plugin for next.js (next-optimized-images) and don't want to force the users to install a beta version or implement two different handlers for each version in the plugin. Thanks!

**Comment by herrstucki** [comment]
@cyrilwanner Done! Let me know if it works in your plugin or if anything is missing.

**Comment by cyrilwanner** [comment]
It works perfectly, thank you very much!

**Pull request merged**
