### PR TITLE
Sharp and webpack 2 support (aka v1 🌟)

### PR DESCRIPTION
**Pull request by herrstucki**
Adds support for processing images using [sharp](http://sharp.dimens.io/en/stable/) which is much faster than Jimp or even ImageMagick.

I built on top of @langri-sha's [work](https://github.com/langri-sha/responsive-loader/tree/sharp) mentioned in #2, but instead of replacing Jimp, I added sharp as an option. Currently, you can enable it by specifying it as an `adapter` in the webpack config (default is still Jimp):

```js
{
  responsiveLoader: {
    adapter: require('responsive-loader/lib/adapters/sharp')
  }
}
```

Auto-detection of sharp could still be added. This approach has the nice benefit that anyone can supply their own adapters once the API is stable.

I also reorganized and changed a few things, most notably:

- added a Babel build step to ensure Node 4 compatibility (I also want to add Flow types at some point, this prepares for that)
- replaced tape with Jest because [snapshots](http://facebook.github.io/jest/docs/api.html#tomatchsnapshotstring) are super-nice to test a loader's output
- added a few more tests to make sure the adapters work in the same way

After some fiddling I got the tests to pass on Travis. sharp builds fine on the `trusty` environment but oddly the output of sharp seems to differ on Linux and macOS, so I had to switch to the `osx` environment in order to make the tests pass. I wonder if there's a better solution to this …

### CODE REVIEW

**Comment by novascreen** [comment]
Any chance you'll merge this soon? Anything I can do to help getting this done?
Otherwise I'll have to find a different solution. Jimp is just too slow especially with a build for server, client and storybook. Takes 1-2 minutes for every start.

**Comment by RichAyotte** [comment]
The performance improvement is dramatic with this patch. I hope you can merge it soon.

**Comment by wereHamster** [comment]
Somebody published this branch as a separate package to NPM: https://www.npmjs.com/package/responsive-loader-sharp, feel free to use that in the meantime.

**Comment by herrstucki** [comment]
That package's README is wrong. I will try to finish the remaining work in the next few days and release an "official" version.

**Comment by herrstucki** [comment]
Alright, I've just published `v1.0.0-rc.1` including sharp and webpack >= 2 support.

Along the way, I dropped support for webpack 1 and had to change the import syntax a bit. Make sure to read the [change log](https://github.com/herrstucki/responsive-loader/blob/sharp/CHANGELOG.md) and the new [README](https://github.com/herrstucki/responsive-loader/blob/sharp/README.md).

Please test this release and then we'll finally get it out the door 😄 . Thanks for the patience!

PS: I'll be adding the pending new features once this is done.

**Comment by wereHamster** [comment]
I won't be able to test this because my current project still uses webpack 1, and I don't plan to upgrade to webpack 2 in this iteration.

**Comment by RichAyotte** [comment]
Works great. Thanks.

**Comment by herrstucki** [comment]
Merged and released as `v1.0.0` 🎉

**Pull request merged**
